# Generated by Django 6.0.5 on 2026-05-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workspaceinvitation',
            name='workspaces__email_efe80b_idx',
        ),
        migrations.RemoveIndex(
            model_name='workspaceinvitation',
            name='workspaces__token_d7fd99_idx',
        ),
        migrations.RemoveConstraint(
            model_name='workspaceinvitation',
            name='unique_pending_workspace_invitation',
        ),
        migrations.DeleteModel(
            name='WorkspaceInvitation',
        ),
    ]
